### ISSUE TITLE
API unavailable

### ISSUE THREAD

**Issue by MysteryMS** [Androz2091/slash-commands-gui#17]
Hi, folks! Seems like the API you use to get the bot's information now requires authentication.
![image](https://user-images.githubusercontent.com/38635037/123895083-a1718e80-d935-11eb-88be-6db9fff5160c.png)

Is there any workaround?

**Comment by Yan-Jobs** [comment]
@Androz2091

**Comment by DomeQdev** [comment]
@Androz2091 same issue

**Comment by xHyroM** [comment]
https://gcommands-slash-gui.netlify.app/ i make fork

**Comment by Androz2091** [comment]
Is your fork public? @xHyroM 
If so, you can make a pull request here

**Comment by xHyroM** [comment]
> Is your fork public? @xHyroM
> If so, you can make a pull request here

It isn't. Is it enough if I make a pull request where I change the api? I made my own.

**Comment by xHyroM** [comment]
https://github.com/Androz2091/slash-commands-gui/pull/18
