### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by favna** [Androz2091/slash-commands-gui#38]
The website https://slash-commands-gui.androz2091.fr can no longer be reached

**Comment by Androz2091** [comment]
Thank you, this will be fixed within the week

**Comment by Androz2091** [comment]
You can use this link in the meantime https://640a3948b72ca20008b779a5--slash-commands-gui.netlify.app/ ;)
I need to update some infra on my end for the domain to work

**Comment by Androz2091** [comment]
This is now fixed, thank you for your patience.
