### ISSUE TITLE
While creating options under subcommands, it gets stuck on loading.

### ISSUE THREAD

**Issue by UltimateSppy765** [Androz2091/slash-commands-gui#4]
https://user-images.githubusercontent.com/73820738/111895117-5a225a80-8a36-11eb-854b-9e69a2c50473.mp4

While I try to create options under subcommands it gets stuck on loading. I tried to make an option called "words" which took a string as input and it was required, but when I tried to create it just got stuck on loading.

**Comment by Androz2091** [comment]
Thank you for reporting this bug, it has been fixed in v1.3.1 :tada:
