### ISSUE TITLE
Show subcommand/group description next to the subcommand/group

### ISSUE THREAD

**Issue by ririko5834** [Androz2091/slash-commands-gui#6]
Hi, can you add that subcommand or group description will be next to the subcommand/group? 

![image](https://user-images.githubusercontent.com/64729293/112748053-97986200-8fb9-11eb-9244-2da36176215a.png)

**Comment by Androz2091** [comment]
Hello, this is a good idea and will be added 👍

**Comment by Androz2091** [comment]
It has been added
