### ISSUE TITLE
Managing global commands

### ISSUE THREAD

**Issue by gauthier-th** [Androz2091/slash-commands-gui#8]
Hi,
Is there a way to manage global slash commands (for every guilds) and not only slash commands for a specific guild?
If there isn't, shouldn't this be added?

**Comment by NoodlesDev987** [comment]
Yes, just don't enter guild id

**Comment by GeekCornerGH** [comment]
> Yes, just don't enter guild id

@gauthier-th yes, you can do with that method ^. Thanks @NoodlesDev987

**Comment by gauthier-th** [comment]
Oh ok, it wasn't clear
